const dotenv = require("dotenv");

dotenv.config({
  path: "./config.env",
});
const mongoose = require("mongoose");

//////////////////////////////////////////////
////// catching uncaught exception
process.on("uncaughtException", (err) => {
  console.log("uncaught exception .......... shutiing down ğŸ’£ğŸ’£ğŸ’£ğŸ’£ğŸ’£ğŸ’£");
  console.log(err);
  process.exit(1);
});

const app = require("./app");

const DB = process.env.DATABASE.replace(
  "<PASSWORD>",
  process.env.DATABASE_PASSWORD
);
mongoose
  .connect(DB, {
    useNewUrlParser: true,
    useCreateIndex: true,
    useFindAndModify: false,
  })
  .then(() => {
    console.log("connection is stabliished");
  });

const port = process.env.PORT || 3000;
app.listen(port, () => {
  console.log(`App is running on a server ${port} ....`);
});
//created a server

// handling the unhandled error rejection

process.on("unhandledRejection", (err) => {
  // console.log(err.name, err.message);
  console.log("unhandlled rejection .......... shutiing down ğŸ’£ğŸ’£ğŸ’£ğŸ’£ğŸ’£ğŸ’£");
  console.log(err);
  server.close(() => {
    process.exit(1);
  });
});

process.on("uncaughtException", (err) => {
  console.log("uncaught exception .......... shutiing down ğŸ’£ğŸ’£ğŸ’£ğŸ’£ğŸ’£ğŸ’£");
  console.log(err);
  server.close(() => {
    process.exit(1);
  });
});
